name = "Hungry Railways"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00541c38108ee241a2479a3a9c6941f50d8421c7384df8c9a169f4a968780774"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"

[options]
datapack-folder = "datapacks"
