name = "Hungry Railways"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deda97f74de2c99b538ab07a34ad79cdf26014cf5c023eb27b1ada2326e0587a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"

[options]
datapack-folder = "datapacks"
