name = "Hungry Railways"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "422028b3a41feadf2776c80a6942fa5bd7fe36c142f7ac76cd1f0221220ddab3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"

[options]
datapack-folder = "datapacks"
